name: CI Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.22'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Verificar versión de Go
        run: go version

      - name: Cargar variables del archivo .env (si existe)
        run: |
          if [ -f .env ]; then
            cat .env >> $GITHUB_ENV
          fi

      - name: Instalar dependencias
        run: go mod tidy

      - name: Formatear código
        run: make fmt

      - name: Lint (go vet)
        run: make lint

      - name: Compilar proyecto
        run: make build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cargar variables del archivo .env (si existe)
        run: |
          if [ -f .env ]; then
            cat .env >> $GITHUB_ENV
          fi

      - name: Ejecutar pruebas
        run: make test

      - name: Ejecutar cobertura y generar reporte
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
